### ISSUE TITLE
Update of dependency ets-wfs20 to v1.38 leads to error

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20-dgiwg#23]
**Describe the bug**
When dependency ets-wfs20 is updated to v1.38, following error occurs when starting TEAM Engine stand-alone:
```
7ee3e2> SEVERE: The ResourceConfig instance does not contain any root resource classes.
7ee3e2> Aug 30, 2022 12:02:36 PM com.sun.jersey.spi.inject.Errors processErrorMessages
7ee3e2> SEVERE: The following errors and warnings have been detected with resource and/or provider classes:
7ee3e2>   SEVERE: Missing dependency for field: private com.sun.jersey.spi.MessageBodyWorkers com.sun.jersey.multipart.impl.FormDataMultiPartDispatchProvider.mbws
7ee3e2>   SEVERE: Missing dependency for field: private com.sun.jersey.server.impl.model.parameter.multivalued.MultivaluedParameterExtractorProvider com.sun.jersey.multipart.impl.FormDataMultiPartDispatchProvider.mpep
7ee3e2> Aug 30, 2022 12:02:36 PM org.apache.catalina.core.ApplicationContext log
7ee3e2> SEVERE: StandardWrapper.Throwable
7ee3e2> com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
7ee3e2> 	at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
7ee3e2> 	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
7ee3e2> 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
7ee3e2> 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1228)
7ee3e2> 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1172)
7ee3e2> 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
7ee3e2> 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5449)
7ee3e2> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5747)
7ee3e2> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
7ee3e2> 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
7ee3e2> 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
7ee3e2> 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
7ee3e2> 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
7ee3e2> 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2038)
7ee3e2> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
7ee3e2> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
7ee3e2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
7ee3e2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
7ee3e2> 	at java.lang.Thread.run(Thread.java:748)
7ee3e2> 
7ee3e2> Aug 30, 2022 12:02:36 PM org.apache.catalina.core.StandardContext loadOnStartup
7ee3e2> SEVERE: Servlet [TestSuiteController] in web application [/teamengine] threw load() exception
7ee3e2> com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
7ee3e2> 	at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
7ee3e2> 	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
7ee3e2> 	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
7ee3e2> 	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
7ee3e2> 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
7ee3e2> 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1228)
7ee3e2> 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1172)
7ee3e2> 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
7ee3e2> 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5449)
7ee3e2> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5747)
7ee3e2> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
7ee3e2> 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
7ee3e2> 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
7ee3e2> 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
7ee3e2> 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
7ee3e2> 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2038)
7ee3e2> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
7ee3e2> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
7ee3e2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
7ee3e2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
7ee3e2> 	at java.lang.Thread.run(Thread.java:748)
```

Following error occurs when starting TEAM Engine with teamengine-docker project:
```
...
INFO: validateJarFile(/usr/local/tomcat/webapps/te2/WEB-INF/lib/tomcat-servlet-api-7.0.69.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
Aug 26, 2022 4:52:06 PM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/te2]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2038)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/sun/jersey/server/impl/container/servlet/JerseyServletContainerInitializer.addServletWithApplication(Ljavax/servlet/ServletContext;Ljava/lang/Class;Ljava/util/Set;)V @34: invokespecial
  Reason:
    Type 'com/sun/jersey/server/impl/application/DeferredResourceConfig' (current frame, stack[2]) is not assignable to 'javax/ws/rs/core/Application'
  Current Frame:
    bci: @34
    flags: { }
    locals: { 'com/sun/jersey/server/impl/container/servlet/JerseyServletContainerInitializer', 'javax/servlet/ServletContext', 'java/lang/Class', 'java/util/Set', 'javax/ws/rs/ApplicationPath' }
    stack: { uninitialized 17, uninitialized 17, 'com/sun/jersey/server/impl/application/DeferredResourceConfig' }
  Bytecode:
    0x0000000: 2c13 0036 b600 37c0 0036 3a04 1904 c600
    0x0000010: 9fbb 0022 59bb 0038 592c 2a2d b700 21b7
    0x0000020: 0039 b700 253a 052a 1904 b700 3a3a 062a
    0x0000030: 2b19 06b7 003b 9a00 4c2b 2cb6 000a 1905
    0x0000040: b900 2703 0004 bd00 1b59 0319 0653 b900
    0x0000050: 3c02 0057 b200 2abb 002b 59b7 002c 1232
    0x0000060: b600 2e2c b600 0ab6 002e 123d b600 2e19
    0x0000070: 06b6 002e 123e b600 2eb6 0030 b600 35a7
    0x0000080: 002e b200 2abb 002b 59b7 002c 123f b600
    0x0000090: 2e2c b600 0ab6 002e 123d b600 2e19 06b6
    0x00000a0: 002e 1240 b600 2eb6 0030 b600 31b1     
  Stackmap Table:
    append_frame(@130,Object[#155],Object[#147],Object[#156])
    chop_frame(@173,2)

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:197)
	at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:158)
	at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1579)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1273)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:881)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:388)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5606)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 10 more

Aug 26, 2022 4:52:06 PM org.apache.catalina.startup.HostConfig deployDirectory
SEVERE: Error deploying web application directory /usr/local/tomcat/webapps/te2
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/te2]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1022)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2038)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
...
```

**Expected behavior**
Dependency ets-wfs20 shall be updated to the latest version without breaking the test suite/ TEAM Engine.

**Comment by dstenger** [comment]
Issue was solved by https://github.com/opengeospatial/ets-wfs20-dgiwg/pull/33.
